name: PYFloods
channels:
  - conda-forge
dependencies:
  - python=3.6
  - bottleneck
  - cartopy
  - colorcet
  - ipython
  - jupyter
  - matplotlib=2.2
  - netCDF4
  - numba
  - numpy
  - pandas=0.23.0
  - scipy
  - scikit-learn
  - seaborn
  - xarray=0.10.7
  - windspharm
